### ISSUE TITLE
return output from run-command

### ISSUE THREAD

**Issue by tacman** [nadar/php-composer-reader#15]
Currently run-command doesn't do anything with the output.  What do you think about passing it back, with a &$output parameter.

```php
    public function runCommand($command, &$output)
    {
        $folder = dirname($this->file);
        $olddir = getcwd();
        chdir($folder);

        ob_start();
        $output = null;
        $cmd = system('composer ' . $command, $output);
        $output = ob_end_clean();
        chdir($olddir);

        return $cmd !== false;
    }
```

Of course, running processes involving composer are problematic, since the caller still has the data from the original composer.  I have a script where dump the class map with "composer dump" and then stop the process and say "please re-run this command to reload composer with the new settings".

**Comment by nadar** [comment]
assign by ref does not seems to a good solution, but i think i should internaly refactor to have the option for:

->createCommand($command)->run()->getOutput()->isSuccessfull()

and runCommand() will be like the internal form of the above chain.

**Comment by tacman** [comment]
yeah, I've never liked the assign by reference.

This is what I use now, might be interesting to see the signatures there:

https://github.com/zenstruck/console-extra?tab=readme-ov-file#commandrunner

You probably don't want to add any more dependencies, but you could add this as "suggests" if you just wanted to use it instead.

**Comment by nadar** [comment]
you can test the dev-master, running command within php might cause some issue but implementing another dependency just for this don't make sense to me. Then better run the command external.
