### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by jeroenherczeg** [nadar/php-composer-reader#4]
What are your thoughts on the missing properties (name, description, ...)?
Do you think that is something you would like to add to the package?

What do you think about packages/requirements inside the require property. These are mostly packages but often you also find the php version or the php extensions inside this property.
Do you think this package should differentiate between the two?

**Comment by nadar** [comment]
hi @jeroenherczeg 

> What are your thoughts on the missing properties (name, description, ...)?

Or you talking about the "package" itself? like https://github.com/nadar/php-composer-reader/blob/master/composer.json#L2-L3

We could make a meta information class which provides this information. But this informations are only available on packages which are distributed on packagist, if you have a project just using a library trough require there wont be meta information (cause its not needed).

> these are mostly packages but often you also find the php version or the php extensions inside this property.

You mean those informations? https://getcomposer.org/doc/01-basic-usage.md#platform-packages

Good catch! Not sure how to handle those, but basically its also a package with name and constraint. But maybe the package class could have a method which could check for such informations like: `isPlatformPackage()` - or what are you trying to do?

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.
