### ISSUE TITLE
is there  a way i can add or remove require or require-dev packages?

### ISSUE THREAD

**Issue by codeitlikemiley** [nadar/php-composer-reader#6]
other class like Autoload has an add function, 

its odd that require class and require-dev class dont have it...

am i missing something or is it really not baked in this package?

**Comment by codeitlikemiley** [comment]
anyway i figured it out already but if someone would search this , 
this thread might help you..

```
use Nadar\PhpComposerReader\ComposerReader;
use Nadar\PhpComposerReader\RequireSection;

// Instantiate ComposerReader
$reader = new ComposerReader(base_path('composer.json'));
// Instantiate  RequireSection
$section = new RequireSection($reader);

// get current content of require section in composer.json
$packages = $reader->contentSection('require',$section)

// packages to be added
$new_packages = ['beyondcode/laravel-websockets' => '^1.1'];

// merge to new array
$packages = array_merge($packages,$new_packages);

// update the require section in composer.json
$reader->updateSection('require', $packages);

// check if the reader instance has the new updated section
$reader->getContent();

// finally save it
$reader->save();

```

**Comment by nadar** [comment]
Hey @codeitlikemiley, indeed it makes not sense to **not have an add** method as it would be an easy task. I am going to add it.

**Comment by nadar** [comment]
Hey @codeitlikemiley i just pushed a commit in order to allow "add" method also for require sections, would you please give it a try and let me know?

**Comment by codeitlikemiley** [comment]
would test it later , its 3 am in the morning here now , thanks for the new feature, ive probably update my package and remove the custom add function in it. I also had a remove packages function but it uses just plain php filesystem. If u can add it also then that would be great. it is useful for require and require-dev packages. I use it for scaffolding a laravel app dependencies. 

```
$path_to_file = base_path('composer.json');

// The Whole Content of composer.json
$block_of_lines = file_get_contents($path_to_file);

// List of composer packages
$unwanted_words = array("filp/whoops", "fzaninotto/faker", "mockery/mockery");

$unwanted_words_match = '(?:' . join('|', array_map(function($word) {
    return preg_quote($word, '/');
}, $unwanted_words)) . ')';

$replace_match = '/^.*' . $unwanted_words_match . '.*$(?:\r\n|\n)?/m';

$result = preg_replace($replace_match, '', $block_of_lines);

file_put_contents($path_to_file,$result);
```

**Comment by nadar** [comment]
sure, please create a new issue for this feature. thanks
