### ISSUE TITLE
json encode object vs array

### ISSUE THREAD

**Issue by dereuromark** [nadar/php-composer-reader#9]
How do you handle the empty objects in a file without killing it?
I see you are also using 

    $json = json_encode($data, JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);

But if you for example have a file like
```
  "autoload": {
    "psr-4": {
      "Orm\\": "src/Orm/"
    }
  },
  "autoload-dev": {},
```

My script (and yours) would break with the empty autoload-dev.
The result would be after read+ write:
```
  "autoload": {
    "psr-4": {
      "Orm\\": "src/Orm/"
    }
  },
  "autoload-dev": [],
```

The json is now invalid with

> - autoload-dev : Array value found, but an object is required

I tried `JSON_FORCE_OBJECT` but it converts too much. We only need the conversation of array to empty object for specific keys.

I was wondering what your take on this is.
We could remove those keys, but that would increase the diff - and maybe they were already added for a reason.
And manual str_replace sounds a bit hacky.

**Comment by dereuromark** [comment]
Small update

This little hack seems to do the trick:
```php
    $objectKeys = ['require', 'require-dev', 'autoload', 'autoload-dev', 'config', 'scripts'];
        foreach ($objectKeys as $objectKey) {
            if (!isset($array[$objectKey]) || !empty($array[$objectKey])) {
                continue;
            }

            $array[$objectKey] = new \stdClass();
        }
```

**Comment by nadar** [comment]
Thanks for the report, yes i should fix this :+1: 

`$array[$objectKey] = (object) [];` should work to.

**Comment by nadar** [comment]
If a section is empty, we could just remove it i would say. What do you think? I don't think there is any situation required where you need an empty definition.

**Comment by dereuromark** [comment]
In my case I have to keep them as I wanted to keep the diff minimal (that gets commited/PRed).
But I don't know yours.

**Comment by nadar** [comment]
I think there is no technical reason to keep those empty values, its much more easy to say "hey there is an empty array, we just remove that key" instead of doing those "if autoload, or require and empty, then convert to object".

So i would suggest to fix that by removing empty arrays :-/ If you agree on this, i will implement this solution.

**Comment by dereuromark** [comment]
Well, I am only modifying existing code and adding or removing into it, what is necessary for the job.
I don't want to do more than that. So I try to keep side effects to a minimum.

In your case that's either something you decide or you make configurable.
Either way :) I think the issue is minimal, no big deal.

I will close this ticket then.
